### PR TITLE
Load images with an event listener.

### PR DESCRIPTION
**Pull request by robindevitt**
Related issue - https://github.com/humanmade/product-dev/issues/1246

Currently the images are loaded during the page load. This PR adds an event listener that allows the images to be loaded without a page load, this is mainly useful when previewing content with personalised blocks as an admin.

The event listener would be:
```javascript
window.dispatchEvent( new CustomEvent( 'gaussholder.loadImages' ) );
```

A video of this change in action where I have added the event listener to the AWS Analytics module to load the images when previewing a different audience's content ( this is how the issue was originally identified ).

https://user-images.githubusercontent.com/16571365/197757022-3d169ba3-d103-4292-8186-07e7e79f4be1.mp4

### CODE REVIEW

**Comment by roborourke** [comment]
This will work but given this is for external scripts to use - those scripts will know when to trigger Gaussholder, so those will be handling whatever events they need.

Rather than 3rd party code dispatching an event, all we really need here is to expose a function that can be called. For example:

```
// `some-custom-event` is triggered by 3rd party code
window.addEventListener( 'some-custom-event', function () {
    // run gaussholder load images function
    window.gaussholderLoadImages();
} )
```

**Comment by robindevitt** [comment]
@roborourke is this simplified approach what you referred too - https://github.com/humanmade/Gaussholder/pull/71/files

**Comment by roborourke** [comment]
That's requiring 3rd party code to create and dispatch a custom event still.

I meant all you need to do is expose the Gaussholder function on the window object. e.g.

```
window.GaussHolder = GaussHolder;
```

Then other code can call `GaussHolder();` at the appropriate time.

**Review by roborourke — APPROVED** [review]
Technically we're adding a feature here but it's primarily going to be used for bug fixes in other code, and is non-breaking so we can go with the patch version update.

**Comment by robindevitt** [comment]
Cheers Rob 🍻 I was in two minds on the correct version to bump it to.

**Pull request merged**
